export const dummyListings = [
    {
      id: 1,
      title: "Golden Retriever Puppy (Male)",
      category: "pet",
      price: 45000,
      imageUrl: "https://images.unsplash.com/photo-1633722715463-d30f4f325e24?w=500&auto=format&fit=crop&q=60",
      sellerName: "Ali Khan",
      location: "Lahore",
    },
    {
      id: 2,
      title: "Premium Royal Canin Dog Food (15kg)",
      category: "accessory",
      price: 18500,
      imageUrl: "/images/dog_food.jpg",
      sellerName: "Pet Store PK",
      location: "Karachi",
    },
    {
      id: 3,
      title: "Persian Cat (Female, 6 months)",
      category: "pet",
      price: 35000,
      imageUrl: "https://images.unsplash.com/photo-1513245543132-31f507417b26?w=500&auto=format&fit=crop&q=60",
      sellerName: "Sara Ahmed",
      location: "Islamabad",
    },
    {
      id: 4,
      title: "Orthopedic Pet Bed (Large)",
      category: "accessory",
      price: 6500,
      imageUrl: "https://images.unsplash.com/photo-1591946614720-90a587da4a36?w=500&auto=format&fit=crop&q=60",
      sellerName: "Cozy Pets",
      location: "Rawalpindi",
    },
    {
      id: 5,
      title: "Siamese Kitten (Vaccinated)",
      category: "pet",
      price: 25000,
      imageUrl: "https://images.unsplash.com/photo-1513360371669-4adf3dd7dff8?w=500&auto=format&fit=crop&q=60",
      sellerName: "Feline Friends",
      location: "Lahore",
    },
    {
      id: 6,
      title: "Automatic Water Fountain for Cats",
      category: "accessory",
      price: 4200,
      imageUrl: "https://images.unsplash.com/photo-1545249390-6bdfa286032f?w=500&auto=format&fit=crop&q=60",
      sellerName: "Pet Store PK",
      location: "Karachi",
    },
  ];